Name = "Super Elevator"

[[Render]]
    Regex       = "...."
    DisplayList = "gSuperElevatorObj_DlSuperElevatorObj"
    Scale       = 0.01
[[Property]]
    Mask      = 0xFF00
    Name      = "Switch Flags"
    Target    = "Var"
[[Property]]
    Mask      = 0x00F0
    Name      = "Move Dis(X * 100)"
    Target    = "Var"
[[Property]]
    Mask      = 0x000F
    Name      = "reversed"
    Target    = "Var"
    Dropdown = [
		[ 0, "No Reversed"      ],
		[ 1, "Set Switch"       ],
	]