medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Sheik_Struggle"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Zelda_Child_Throw"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cold"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Trumpet1"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E5"
		split_lo = "A1"
		release_rate = 225
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pizzicato_Prim"
			tuning = 2.118926
		[inst.entry.hi]
			sample = "Inst_Pizzicato_Hi"
			tuning = 0.561231
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Sheik_Grunt"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cold"
			tuning = 0.689062
		[inst.entry.hi]
