medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Clap"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 214
		env_rate = [
			2,
			146,
			32,
			-1
		]
		env_level = [
			32701,
			29067,
			1,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Marimba_Bass"
			tuning = 0.579431
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "B5"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			121,
			1,
			-1
		]
		env_level = [
			32701,
			1652,
			1,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Marimba_Prim"
			tuning = 0.890899
		[inst.entry.hi]
			sample = "Inst_Marimba_Hi"
			tuning = 0.445449
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "D5"
		release_rate = 239
		env_rate = [
			2,
			131,
			523,
			-1
		]
		env_level = [
			32701,
			4955,
			1,
			0
		]
		[inst.entry.low]
			sample = "Inst_Guitar_Banjo_Prim"
			tuning = 1.781798
		[inst.entry.prim]
			sample = "Inst_Guitar_Banjo_Hi"
			tuning = 1.189207
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "G3"
		release_rate = 92
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "D5"
		release_rate = 239
		env_rate = [
			2,
			131,
			523,
			-1
		]
		env_level = [
			32701,
			4955,
			1,
			0
		]
		[inst.entry.low]
			sample = "Inst_Guitar_Banjo_Prim"
			tuning = 1.781798
		[inst.entry.prim]
			sample = "Inst_Guitar_Banjo_Hi"
			tuning = 1.189207
		[inst.entry.hi]
