medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			17, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Zummara"
			tuning = 0.445449
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 225
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Metal_Hit"
			tuning = 0.868031
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Trumpet2"
			tuning = 0.667420
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Clarinet"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G4"
		release_rate = 107
		env_rate = [
			2, 1, 422, -1,
		]
		env_level = [
			32701, 32701, 1, 0,
		]
		[inst.entry.low]
			sample = "Perc_Gong"
			tuning = 2.996615
		[inst.entry.prim]
			sample = "Perc_Bell_Chimes"
			tuning = 0.500565
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Conga_Bent"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 9
		env_rate = [
			2, 298, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Scream"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 97
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cave"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "G#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			2, 298, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Zelda_Child_Gasp2"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Npc_Zelda_Child_Gasp2"
			tuning = 1.000000
[drum]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.222725
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.235969
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.250000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.264866
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.280616
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.297302
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.314980
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.333710
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.353553
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.374577
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.396850
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.420448
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.445449
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.471937
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.500000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.529732
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.561231
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.594604
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.629961
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.667420
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.707107
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.749154
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.793701
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.840897
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.890899
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 0.943875
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 59
		release_rate = 0
		sample = "Perc_Tambourine_Rim"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 71
		release_rate = 0
		sample = "Perc_Tambourine_Head"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 71
		release_rate = 0
		sample = "Perc_Tambourine_Head"
		tuning = 1.059463
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.059463
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.122462
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.189207
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.259921
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.334840
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.414214
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.498307
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.587401
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.681793
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.781798
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 1.887749
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.118926
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.244924
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.378414
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.519842
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.669680
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.828428
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 2.996615
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 3.174803
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 3.363586
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 3.563596
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 3.775498
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 4.000000
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 4.237853
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 4.489849
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 4.756829
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 5.039685
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 5.339360
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 5.656855
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 5.993229
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 6.349606
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 6.727173
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]
	[[drum.entry]]
		pan = 75
		release_rate = 0
		sample = "Perc_Tambourine_Cymbal"
		tuning = 7.127192
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32701, 12883, 1, 0,
		]

