medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Sheik_Struggle"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Synth_String"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 246
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Harmonica"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Sheik_Scream"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Zelda_Child_Throw"
			tuning = 1.000000
		[inst.entry.hi]

