medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "F#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			21, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Choir_Female_Prim"
			tuning = 0.516214
		[inst.entry.hi]
			sample = "Inst_Choir_Female_Hi"
			tuning = 0.365018
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 214
		env_rate = [
			2, 146, 32, -1,
		]
		env_level = [
			32701, 29067, 1, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Marimba_Bass"
			tuning = 0.579431
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E5"
		split_lo = "A1"
		release_rate = 225
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pizzicato_Prim"
			tuning = 2.118926
		[inst.entry.hi]
			sample = "Inst_Pizzicato_Hi"
			tuning = 0.561231
	[[inst.entry]]
		split_hi = "E5"
		split_lo = "A1"
		release_rate = 225
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pizzicato_Prim"
			tuning = 2.118926
		[inst.entry.hi]
			sample = "Inst_Pizzicato_Hi"
			tuning = 0.561231
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 245
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Guitar_Bass"
			tuning = 2.381102
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 116
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Bamboo"
			tuning = 1.059463
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 92
		env_rate = [
			42, 298, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pad_Voice"
			tuning = 0.750000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 116
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Bamboo"
			tuning = 1.059463
		[inst.entry.hi]

