medium_type = "cart"
sequence_player = "bgm"
[[inst.entry]]
		split_hi = "E12"
		split_lo = "G4"
		release_rate = 174
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 0, 0, 0,
		]
		[inst.entry.low]
			sample = "Inst_Bouzouki_Prim"
			tuning = 1.781798
		[inst.entry.prim]
			sample = "Inst_Bouzouki_Hi"
			tuning = 0.890899
		[inst.entry.hi]
[inst]
	[[inst.entry]]
		split_hi = "F5"
		split_lo = "G3"
		release_rate = 92
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
		[inst.entry.low]
			sample = "Inst_Piano_Low"
			tuning = 2.317721
		[inst.entry.prim]
			sample = "Inst_Piano_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Piano_Hi"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "B5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Organ_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Organ_Hi"
			tuning = 0.500000
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Chant_Prayer"
			tuning = 0.125000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C5"
		release_rate = 235
		env_rate = [
			2, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_Shine_Dark"
			tuning = 1.498307
		[inst.entry.prim]
			sample = "Inst_Drone_Drip"
			tuning = 0.250000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C#4"
		release_rate = 232
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Perc_Conga_Mute"
			tuning = 1.000000
		[inst.entry.prim]
			sample = "Perc_Conga_Bass"
			tuning = 1.227770
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "F#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			21, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Choir_Female_Prim"
			tuning = 0.516214
		[inst.entry.hi]
			sample = "Inst_Choir_Female_Hi"
			tuning = 0.365018
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Conga_Bent"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 105
		env_rate = [
			50, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Drone_Machine"
			tuning = 1.000000
		[inst.entry.hi]