medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 102
		env_rate = [
			2,
			298,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pad_Voice"
			tuning = 0.750000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G#4"
		release_rate = 185
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.974482
		[inst.entry.prim]
			sample = "Inst_Choir_Male_Prim"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Creek"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 97
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cave"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Clap"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C#4"
		release_rate = 232
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Perc_Conga_Mute"
			tuning = 1.000000
		[inst.entry.prim]
			sample = "Perc_Conga_Bass"
			tuning = 1.227770
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 236
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Ocarina"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "B5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Organ_Prim"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Inst_Organ_Hi"
			tuning = 0.500000
[drum]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.385846
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.408790
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.433098
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.458851
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.486136
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.515043
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.545669
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.578117
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.612493
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.648914
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.687500
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.728381
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.771693
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.817580
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.866196
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 18
		release_rate = 241
		sample = "Perc_Bass_Drum"
		tuning = 0.917703
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 50
		release_rate = 241
		sample = "Perc_Snare_Hard"
		tuning = 1.000000
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 50
		release_rate = 241
		sample = "Perc_Snare_Hard"
		tuning = 1.059463
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 54
		release_rate = 241
		sample = "Perc_Snare_Soft"
		tuning = 1.059463
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 54
		release_rate = 241
		sample = "Perc_Snare_Soft"
		tuning = 1.122462
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 54
		release_rate = 241
		sample = "Perc_Snare_Soft"
		tuning = 1.189207
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.667420
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.707107
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.749154
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.793701
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.840897
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.890899
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 0.943875
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 1.000000
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 1.059463
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 1.122462
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 1.189207
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 28
		release_rate = 241
		sample = "Perc_Cymbal"
		tuning = 1.259921
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.353553
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.374577
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.396850
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.420448
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.445449
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.471937
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.500000
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.529732
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.561231
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.594604
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.629961
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.667420
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.707107
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.749154
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.793701
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.840897
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.890899
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 0.943875
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.000000
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.059463
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.122462
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.189207
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.259921
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.334840
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.414214
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.498307
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.587401
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.681793
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.781798
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 1.887749
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
	[[drum.entry]]
		pan = 74
		release_rate = 241
		sample = "Perc_Timpani"
		tuning = 2.000000
		env_rate = [
			2,
			298,
			1,
			-1
		]
		env_level = [
			32701,
			1,
			1,
			0
		]
