medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "B5"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			121,
			1,
			-1
		]
		env_level = [
			32701,
			1652,
			1,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Zelda_Child_Gasp1"
			tuning = 0.890899
		[inst.entry.hi]
			sample = "Npc_Zelda_Child_Gasp1"
			tuning = 0.445449
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G4"
		release_rate = 107
		env_rate = [
			2,
			1,
			422,
			-1
		]
		env_level = [
			32701,
			32701,
			1,
			0
		]
		[inst.entry.low]
			sample = "Perc_Gong"
			tuning = 2.996615
		[inst.entry.prim]
			sample = "Perc_Bell_Chimes"
			tuning = 0.500565
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C5"
		release_rate = 92
		env_rate = [
			2,
			298,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_Shine_Dark"
			tuning = 1.498307
		[inst.entry.prim]
			sample = "Inst_Shine_Dark"
			tuning = 0.250000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "C5"
		release_rate = 92
		env_rate = [
			2,
			298,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_Drone_Drip"
			tuning = 1.498307
		[inst.entry.prim]
			sample = "Inst_Drone_Drip"
			tuning = 0.250000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 9
		env_rate = [
			2,
			298,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Scream"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G#4"
		release_rate = 185
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.974482
		[inst.entry.prim]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G#4"
		release_rate = 185
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.974482
		[inst.entry.prim]
			sample = "Inst_Choir_Male_Low"
			tuning = 0.689062
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "G#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			2, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Harp_Prim"
			tuning = 0.750000
		[inst.entry.hi]
			sample = "Inst_Harp_Hi"
			tuning = 0.375000
	[[inst.entry]]
		split_hi = "G#5"
		split_lo = "A1"
		release_rate = 211
		env_rate = [
			2,
			298,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Zelda_Child_Gasp"
			tuning = 1.000000
		[inst.entry.hi]
			sample = "Npc_Zelda_Child_Gasp"
			tuning = 1.000000
	[[inst.entry]]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 97
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cave"
			tuning = 1.000000
		[inst.entry.hi]
