medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "C#4"
		split_lo = "C4"
		release_rate = 0
		env_rate = [
			2, 298, 1, -1,
		]
		env_level = [
			32700, 12882, 0, 0,
		]
		[inst.entry.low]
			sample = "Perc_Tambourine_Rim"
			tuning = 2.118926
		[inst.entry.prim]
			sample = "Perc_Tambourine_Head"
			tuning = 2.000000
		[inst.entry.hi]
			sample = "Perc_Tambourine_Cymbal"
			tuning = 1.781798
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 215
		env_rate = [
			2, 145, 31, -1,
		]
		env_level = [
			32700, 29067, 0, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Marimba_Bass"
			tuning = 0.579431
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 105
		env_rate = [
			50, 298, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Drone_Machine"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 93
		env_rate = [
			69, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pad_Flute"
			tuning = 1.334840
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 248
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Beat_Kick"
			tuning = 4.000000
		[inst.entry.hi]	
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 247
		env_rate = [
			2, 1, 32701, -1,
		]
		env_level = [
			32701, 32701, 29431, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Perc_Conga_Bent"
			tuning = 0.500000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 98
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Wind_Cave"
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 117
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Bamboo"
			tuning = 1.059463
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Chant_Prayer"
			tuning = 0.125000
		[inst.entry.hi]
[drum]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.210224
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.222724
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.235969
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.250000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.264866
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.280616
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.297302
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.314981
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.333710
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.353554
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.374577
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.396850
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.420449
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.445450
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.471938
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.500000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.529732
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.561231
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.594603
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.629960
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 31
		release_rate = 233
		sample = "Perc_Conga_Mute"
		tuning = 0.667420
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.353553
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.374577
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.396850
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.420448
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.445449
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.471937
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.500000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.529732
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.561231
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.594604
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.629961
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.667420
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.707107
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.749154
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.793701
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.840897
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.890899
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 0.943875
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 46
		release_rate = 233
		sample = "Perc_Conga_Open"
		tuning = 1.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.300777
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.378125
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.460072
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.546893
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.638876
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.736328
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.839576
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 1.948964
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.064855
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.187638
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.317721
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.455540
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.601554
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.756250
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 2.920146
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 3.093786
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 3.277752
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 3.472658
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 3.679153
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 79
		release_rate = 233
		sample = "Perc_Conga_Bass"
		tuning = 3.897927
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 108
		release_rate = 233
		sample = "Perc_Shaker"
		tuning = 1.000000
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 108
		release_rate = 233
		sample = "Perc_Shaker"
		tuning = 1.059463
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 108
		release_rate = 233
		sample = "Perc_Shaker"
		tuning = 1.122462
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
	[[drum.entry]]
		pan = 108
		release_rate = 233
		sample = "Perc_Shaker"
		tuning = 1.189207
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]

