medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Sheik_Struggle" # UROS_Keys_10_C
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 215
		env_rate = [
			2, 145, 31, -1,
		]
		env_level = [
			32700, 29067, 0, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Nabooru_Scream" # WindWater
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E5"
		split_lo = "A1"
		release_rate = 225
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pizzicato_Prim"
			tuning = 2.118926
		[inst.entry.hi]
			sample = "Inst_Pizzicato_Hi"
			tuning = 0.561231
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "G4"
		release_rate = 108
		env_rate = [
			2, 1, 421, -1,
		]
		env_level = [
			32700, 32700, 0, 0,
		]
		[inst.entry.low]
			sample = "Perc_Gong"
			tuning = 2.996615
		[inst.entry.prim]
			sample = "Perc_Bell_Chimes"
			tuning = 0.500565
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 180 #234
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pad_Voice"
			tuning = 0.750000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 236
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Ocarina"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Link_Child_Idle_Yawn1"	# French Horn
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2,
			1,
			32701,
			-1
		]
		env_level = [
			32701,
			32701,
			29431,
			0
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Ruto_Laugh" # TS_VK_kick_motown
			tuning = 1.000000
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Npc_Nabooru_Struggle"	# Iceland
			tuning = 1.000000
		[inst.entry.hi]
