#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "F#5"
		split_lo = "A1"
		release_rate = 234
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Guitar_Nylon_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_Guitar_Nylon_Hi"
			tuning = 0.420448
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 215
		env_rate = [
			2, 145, 31, -1,
		]
		env_level = [
			32700, 29067, 0, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Marimba_Bass"
			tuning = 0.579431
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "E5"
		split_lo = "A1"
		release_rate = 40
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pizzicato_Prim"
			tuning = 2.118926
		[inst.entry.hi]
			sample = "Inst_Pizzicato_Hi"
			tuning = 0.561231
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 239
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Horn"
			tuning = 1.000000
		[inst.entry.hi]