#medium_type = "ram" / "unk"     / "cart" / "ddrive"
#sequence_player = "sfx" / "fanfare" / "bgm"  / "demo"
medium_type = "cart"
sequence_player = "bgm"
[inst]
	[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 300
		env_rate = [
			10, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Pad_Flute"
			tuning = 1.334840
		[inst.entry.hi]
[[inst.entry]]
		split_hi         = "G#5"
		split_lo         = "A1"
		release_rate     = 60
env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample           = "Inst_Pizzicato_Prim"
			tuning           = 2.118926
		[inst.entry.hi]
			sample           = "Inst_Pizzicato_Hi"
			tuning           = 0.561231
	[[inst.entry]]
		split_hi         = "G#5"
		split_lo         = "A1"
release_rate = 100
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
[inst.entry.low]
		[inst.entry.prim]
			sample           = "Inst_Harp_Prim"
			tuning           = 0.750000
		[inst.entry.hi]
			sample           = "Inst_Harp_Hi"
			tuning           = 0.375000
			[[inst.entry]]
		split_hi = "E12"
		split_lo = "A1"
		release_rate = 1000
		env_rate = [
			10, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
		[inst.entry.prim]
			sample = "Inst_Ocarina"
			tuning = 0.629961
		[inst.entry.hi]
	[[inst.entry]]
		split_hi = "C#5"
		split_lo = "D#4"
		release_rate = 235
		env_rate = [
			2, 1, 32700, -1,
		]
		env_level = [
			32700, 32700, 29430, 0,
		]
		[inst.entry.low]
			sample = "Inst_String_Low"
			tuning = 4.000000
		[inst.entry.prim]
			sample = "Inst_String_Prim"
			tuning = 1.259921
		[inst.entry.hi]
			sample = "Inst_String_Hi"
			tuning = 0.629961