Name = "Switch Pillar"
Category = "BG"

[[Render]]
    Regex = "[0-3]..."
    Segment = 6
    Scale = 0.5
    DisplayList = "gRedblueblock_DlSinglepillar"
    ScaleMask = 0x3C00
    ScaleTarget = "Var"
    ScaleArray = [ 0.5,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5 ]
    ColorMask = 0x03C0
    ColorTarget = "Var"
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
    TextureOffsets = [ "gRedblueblock_TexNormalpillar" ]
[[Render]]
    Regex = "[4-7]..."
    Segment = 6
    Scale = 0.5
    DisplayList = "gRedblueblock_DlTriplepillar"
    ScaleMask = 0x3C00
    ScaleTarget = "Var"
    ScaleArray = [ 0.5,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5 ]
    ColorMask = 0x03C0
    ColorTarget = "Var"
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
    TextureOffsets = [ "gRedblueblock_TexNormalpillar" ]
[[Render]]
    Regex = "[8-9AB]..."
    Segment = 6
    Scale = 0.5
    DisplayList = "gRedblueblock_DlSinglepillar"
    ScaleMask = 0x3C00
    ScaleTarget = "Var"
    ScaleArray = [ 0.5,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5 ]
    ColorMask = 0x03C0
    ColorTarget = "Var"
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
    TextureOffsets = [ "gRedblueblock_TexTriforcepillar" ]
[[Render]]
    Regex = "[CDEF]..."
    Segment = 6
    Scale = 0.5
    DisplayList = "gRedblueblock_DlTriplepillar"
    ScaleMask = 0x3C00
    ScaleTarget = "Var"
    ScaleArray = [ 0.5,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5 ]
    ColorMask = 0x03C0
    ColorTarget = "Var"
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
    TextureOffsets = [ "gRedblueblock_TexTriforcepillar" ]
[[Property]]
	Mask          = 0x4000
	Name          = "Shape"
	Target        = "Var"
	Dropdown = [ [ 0, "Normal"],[ 1, "Wide"]]
[[Property]]
	Mask          = 0x8000
	Name          = "Texture"
	Target        = "Var"
	Dropdown = [ [ 0, "Pillar"],[ 1, "Triforce"]]
[[Property]]
	Mask          = 0x3C00
	Name          = "Scale"
	Target        = "Var"
[[Property]]
	Mask          = 0x03C0
	Name          = "Color"
	Target        = "Var"
	Dropdown = [ [ 0, "Red"],[ 1, "Blue (inverted)"],[ 2, "Green"],[ 3, "Yellow (inverted)"],[ 4, "Purple"],[ 5, "Orange (inverted)"],[ 6, "White"],[ 7, "White (inverted)"] ]
[[Property]]
	Mask          = 0x003F
	Name          = "Switch Flag"
	Target        = "Var"