# KokiriShop
draw_func_index = 0
[enables]
	bottles     = false
	a_button    = false
	b_button    = false
	unused      = true
	warp_song   = false
	ocarina     = true
	hookshot    = false
	trade_item  = false
	other       = false
	din_nayru   = true
	farores     = true
	sun_song    = true
