Name = "Switch Platform"
Category = "BG"

[[Render]]
    Regex = "[012389AB]..."
    Segment = 6
    Scale = 0.01
    DisplayList = "gSwitchPlatformObj_DlSwitchPlatformObj"
    ColorMask = 0x01C0
    ColorTarget = "Var"
    IgnoreRotation = [1,1,1]
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
[[Render]]
    Regex = "[4567CDEF]..."
    Segment = 6
    Scale = 0.01
    DisplayList = "gSwitchPlatformObj_DlSwitchPlatformObj"
    ColorMask = 0x01C0
    ColorTarget = "Var"
    IgnoreRotation = [0,0,1]
    EnvColorArray = [ [0xFF, 0x2B, 0x00, 0xFF], 
    [0x6A, 0x00, 0xFF, 0xFF],
    [0x00, 0xFF, 0x26, 0xFF],
    [0xFF, 0xEC, 0x00, 0xFF],
    [0xAA, 0x32, 0x9B, 0xFF],
    [0xFF, 0x97, 0x3C, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF],
    [0xFF, 0xFF, 0xFF, 0xFF] ]
[[Property]]
	Mask          = 0x4000
	Name          = "Type"
	Target        = "Var"
	Dropdown = [ [ 0, "Use Rotation as waypoint"],[ 1, "Use pathway"]]
[[Property]]
	Mask          = 0x8000
	Name          = "Behaviour"
	Target        = "Var"
	Dropdown = [ [ 0, "Stop after reaching last point, return on off"],[ 1, "Continue till turned off"]]
[[Property]]
	Mask          = 0x3000
	Name          = "Speed"
	Target        = "Var"
    Dropdown = [ [ 0, "Very Slow"],[ 1, "Slow"],[ 2, "Fast"],[ 3, "Very Fast"]]
[[Property]]
	Mask          = 0x0200
	Name          = "End of path behaviour (continue) "
	Target        = "Var"
    Dropdown = [ [ 0, "Never stop"],[ 1, "Stop 1 second at each extreme of the path"]]
[[Property]]
    Mask          = 0x0F00
    Name          = "Pathway ID"
    Target        = "ZRot"
[[Property]]
    Mask          = 0x00FF
    Name          = "Starting waypoint"
    Target        = "ZRot"
[[Property]]
	Mask          = 0x01C0
	Name          = "Color"
	Target        = "Var"
	Dropdown = [ [ 0, "Red"],[ 1, "Blue (inverted)"],[ 2, "Green"],[ 3, "Yellow (inverted)"],[ 4, "Purple"],[ 5, "Orange (inverted)"],[ 6, "White"],[ 7, "White (inverted)"] ]
[[Property]]
	Mask          = 0x003F
	Name          = "Switch Flag"
	Target        = "Var"