bank_id         = [ 0x25 ]
medium_type     = "cart"
sequence_player = "bgm"
sequence_flags  = ["restore", "no_ambience" ]
[seq64]
	master_volume   = 88
	flstudio        = false
	loop            = true
